package com.projectsale.api.integration;
import static org.assertj.core.api.Assertions.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*; import com.fasterxml.jackson.databind.*; import com.projectsale.api.catalog.service.CatalogService; import java.sql.*; import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.context.DynamicPropertyRegistry; import org.springframework.test.context.DynamicPropertySource; import org.springframework.test.web.servlet.MockMvc; import org.testcontainers.containers.PostgreSQLContainer; import org.testcontainers.junit.jupiter.*; import javax.sql.DataSource;
@Testcontainers @SpringBootTest @AutoConfigureMockMvc
class PostgresMigrationTest {
 @Container static final PostgreSQLContainer<?> POSTGRES=new PostgreSQLContainer<>("postgres:17-alpine");
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",POSTGRES::getJdbcUrl);r.add("spring.datasource.username",POSTGRES::getUsername);r.add("spring.datasource.password",POSTGRES::getPassword);r.add("app.jwt.secret-base64",()->"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");}
 @Autowired DataSource dataSource;
 @Autowired JdbcTemplate jdbc;
 @Autowired CatalogService catalog;
 @Autowired MockMvc mvc;
 @Autowired ObjectMapper json;
 @Test void flywayCreatesUuidAndRefreshSchema() throws Exception {try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement("select count(*) from information_schema.columns where table_name='products' and column_name in ('public_id','gender','has_lens','face_tags')");ResultSet rs=p.executeQuery()){assertThat(rs.next()).isTrue();assertThat(rs.getInt(1)).isEqualTo(4);}try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement("select count(*) from information_schema.tables where table_name='refresh_tokens'");ResultSet rs=p.executeQuery()){assertThat(rs.next()).isTrue();assertThat(rs.getInt(1)).isEqualTo(1);}}
 @Test void catalogFiltersAndFullTextSearchRunOnPostgres(){Long category=jdbc.queryForObject("insert into categories(name,slug,status) values ('Frames','frames','ACTIVE') returning id",Long.class);Long brand=jdbc.queryForObject("insert into brands(name,slug,status) values ('Acme','acme','ACTIVE') returning id",Long.class);Long product=jdbc.queryForObject("insert into products(category_id,brand_id,name,slug,description,min_price,gender,has_lens,face_tags,status) values (?,?, 'Titan Frame','titan-frame','Light titanium glasses',120.00,'unisex',true,ARRAY['oval']::varchar(32)[],'ACTIVE') returning id",Long.class,category,brand);Long other=jdbc.queryForObject("insert into products(category_id,brand_id,name,slug,description,min_price,gender,has_lens,face_tags,status) values (?,?, 'Square Frame','square-frame','Square glasses',110.00,'unisex',true,ARRAY['square']::varchar(32)[],'ACTIVE') returning id",Long.class,category,brand);jdbc.update("insert into product_variants(product_id,sku,color,price,stock_qty) values (?,'SKU-1','Black',120.00,5)",product);jdbc.update("insert into product_variants(product_id,sku,color,price,stock_qty) values (?,'SKU-2','Black',110.00,5)",other);var filtered=catalog.list(null,null,null,null,"black","UNISEX",true,"OVAL",0,20,"name,asc");assertThat(filtered.getContent()).extracting(x->x.slug()).containsExactly("titan-frame");var searched=catalog.search("titan",0,20,"name,asc");assertThat(searched.getContent()).extracting(x->x.slug()).containsExactly("titan-frame");}
 @Test void registerAndRefreshRotateDatabaseToken() throws Exception {String register="{\"email\":\"auth@example.com\",\"password\":\"StrongPass123\",\"full_name\":\"Auth User\"}";String body=mvc.perform(post("/api/v1/auth/register").contentType(MediaType.APPLICATION_JSON).content(register)).andExpect(status().isCreated()).andExpect(jsonPath("$.data.user.id").isNotEmpty()).andReturn().getResponse().getContentAsString();String old=json.readTree(body).get("data").get("refresh_token").asText();String refresh="{\"refresh_token\":\""+old+"\"}";String rotated=mvc.perform(post("/api/v1/auth/refresh").contentType(MediaType.APPLICATION_JSON).content(refresh)).andExpect(status().isOk()).andExpect(jsonPath("$.data.access_token").isNotEmpty()).andExpect(jsonPath("$.data.refresh_token").isNotEmpty()).andReturn().getResponse().getContentAsString();assertThat(json.readTree(rotated).get("data").get("refresh_token").asText()).isNotEqualTo(old);mvc.perform(post("/api/v1/auth/refresh").contentType(MediaType.APPLICATION_JSON).content(refresh)).andExpect(status().isUnauthorized());}
 @Test void loginMeAndLogoutRevokeSession() throws Exception {String register="{\"email\":\"session@example.com\",\"password\":\"StrongPass123\",\"full_name\":\"Session User\"}";mvc.perform(post("/api/v1/auth/register").contentType(MediaType.APPLICATION_JSON).content(register)).andExpect(status().isCreated());String login="{\"email\":\"session@example.com\",\"password\":\"StrongPass123\"}";JsonNode session=json.readTree(mvc.perform(post("/api/v1/auth/login").contentType(MediaType.APPLICATION_JSON).content(login)).andExpect(status().isOk()).andReturn().getResponse().getContentAsString());String access=session.get("data").get("access_token").asText(),refresh=session.get("data").get("refresh_token").asText();mvc.perform(get("/api/v1/me").header("Authorization","Bearer "+access)).andExpect(status().isOk()).andExpect(jsonPath("$.data.email").value("session@example.com"));mvc.perform(post("/api/v1/auth/logout").header("Authorization","Bearer "+access).contentType(MediaType.APPLICATION_JSON).content("{\"refresh_token\":\""+refresh+"\"}")).andExpect(status().isOk());mvc.perform(post("/api/v1/auth/refresh").contentType(MediaType.APPLICATION_JSON).content("{\"refresh_token\":\""+refresh+"\"}")).andExpect(status().isUnauthorized());}
}
